### ISSUE TITLE
új pull request hiba

### ISSUE THREAD

**Issue by kohalmykristof** [gyulanemeth/game-of-life-js#1]
Szia!
Nem tudok új pull request-et létrehozni, nincs hozzá külső felhasználónak jogosultsága.
Egy fél óra után azt is meguntam, hogy próbáljak publikálni valahogy a github-ra saját felhasználónévvel :D.
Feltettem users-re a következő linkre:
http://users.itk.ppke.hu/~kohkr/game_of_life_js
Változás: width/height átadás tervezési hiba javítás, play/pause, reset, design (mérethez kicsit igazodó) és inicializálások kerültek bele (kezdeti kirajzolások, kezdőállapot). Memory leak elkerülésére figyeltem (elvileg). Némi átstrukturálás is történt, pl. a kirajzolás vagy az állapotmátrix random értékekkel feltöltése függvénybe lett kiemelve, új paraméterek és eseménykezelő függvények.
Kőhalmy Kristóf

**Comment by gyulanemeth** [comment]
Az én repómat forkoltad? Úgy pedig mennie kéne... Megnéztem a tiédet és üresnek tűnik, ezért merült fel bennem a kérdés. Amúgy jól néz ki nagyon, amit csináltál, úgyhogy kéne az a pull request mindenképp ;)

**Comment by kohalmykristof** [comment]
Áááá, "that's where the magic happens" :). Így már sikerült, köszönöm!
